config/routes.rb
Rails.application.routes.draw do
  root "home#index"

  get '/login', :to => 'sessions#new', :as => 'login'
  post '/login', :to => 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/password-reset', to: 'passwords#new', as: 'new_password_reset'
  post '/password-reset', to: 'passwords#create', as: 'password_reset'

  get '/password-confirmation', to: 'confirmations#new', as: 'new_password'
  post '/password-confirmation', to: 'passwords#update', as: 'edit_password'

  post 'tokens' => 'tokens#create'

  resources :users, only: [:new, :create, :edit, :update]

  resources :currencies, only: [:show], id: "bitcoin"
  resources :bitcoin, only: [:index]
  resources :ethereum, only: [:index]

  namespace :charts do
    namespace :bitcoin do
      get "avg_btc_open_monthly"
      get "avg_btc_open_yearly"
      get "avg_btc_high_monthly"
      get "avg_btc_high_yearly"
      get "avg_btc_low_monthly"
      get "avg_btc_low_yearly"
      get "avg_btc_close_monthly"
      get "avg_btc_close_yearly"
    end
    namespace :ethereum do
      get "avg_eth_open_monthly"
      get "avg_eth_open_yearly"
      get "avg_eth_high_monthly"
      get "avg_eth_high_yearly"
      get "avg_eth_low_monthly"
      get "avg_eth_low_yearly"
      get "avg_eth_close_monthly"
      get "avg_eth_close_yearly"
    end
  end
end

app/models/bitcoin.rb
class Bitcoin < ApplicationRecord
  validates :date,
            :open,
            :high,
            :low,
            :close,
            presence: true

  def self.average_yearly_open
    group_by_year(:date)
    .average(:open)
  end

  def self.average_monthly_open
    group_by_month(:date)
    .average(:open)
  end

  def self.average_yearly_high
    group_by_year(:date)
    .average(:high)
  end
  def self.average_monthly_high
    group_by_month(:date)
    .average(:high)
  end

  def self.average_yearly_low
    group_by_year(:date)
    .average(:low)
  end

  def self.average_monthly_low
    group_by_month(:date)
    .average(:low)
  end

  def self.average_yearly_close
    group_by_year(:date)
    .average(:close)
  end

  def self.average_monthly_close
    group_by_year(:date)
    .average(:close)
  end
end

app/controllers/bitcoin_controller.rb
class BitcoinController < ApplicationController
  def index
    @bitcoins = Bitcoin.all.paginate(page: params[:page], per_page: 20)
  end
end

app/controllers/charts/bitcoin_controller.rb
class Charts::BitcoinController < ApplicationController

  def avg_btc_open_monthly
    render json: Bitcoin.average_monthly_open
  end

  def avg_btc_open_yearly
    render json: Bitcoin.average_yearly_open
  end

  def avg_btc_high_monthly
    render json: Bitcoin.average_monthly_high
  end

  def avg_btc_high_yearly
    render json: Bitcoin.average_yearly_high
  end

  def avg_btc_low_monthly
    render json: Bitcoin.average_monthly_low
  end

  def avg_btc_low_yearly
    render json: Bitcoin.average_yearly_low
  end

  def avg_btc_close_monthly
    render json: Bitcoin.average_monthly_close
  end

  def avg_btc_close_yearly
    render json: Bitcoin.average_yearly_close
  end

end

app/views/bitcoin/index.html.erb
<%= render partial: 'layouts/navbar' %>
<div class="content-wrapper container">
  <h1>Bitcoin Historical Data</h1>
  <hr>
  <% cache(charts_bitcoin_avg_btc_open_monthly_path, expires_in: 6.hours) do %>
  <h3>Average Open Price By Month</h3>
    <%= line_chart charts_bitcoin_avg_btc_open_monthly_path, refresh: 60 %>
    <% end %>
  <hr>
  <h3>Average Open Price By Year</h3>
    <%= line_chart charts_bitcoin_avg_btc_open_yearly_path, refresh: 60 %>
  <hr>
  <% cache(charts_bitcoin_avg_btc_high_monthly_path, expires_in: 6.hours) do %>
  <h3>Average High Price By Month</h3>
    <%= line_chart charts_bitcoin_avg_btc_high_monthly_path, refresh: 60 %>
    <% end %>
  <hr>
  <h3>Average High Price By Year</h3>
    <%= line_chart charts_bitcoin_avg_btc_high_yearly_path, refresh: 60 %>
  <hr>
  <% cache(charts_bitcoin_avg_btc_low_monthly_path, expires_in: 6.hours) do %>
  <h3>Average Low Price By Month</h3>
    <%= line_chart charts_bitcoin_avg_btc_low_monthly_path, refresh: 60 %>
    <% end %>
  <hr>
  <h3>Average Low Price By Year</h3>
    <%= line_chart charts_bitcoin_avg_btc_low_yearly_path, refresh: 60 %>
  <hr>
  <% cache(charts_bitcoin_avg_btc_close_monthly_path, expires_in: 6.hours) do %>
  <h3>Average Closing Price By Month</h3>
    <%= line_chart charts_bitcoin_avg_btc_close_monthly_path, refresh: 60 %>
    <% end %>
  <hr>
  <h3>Average Closing Price By Year</h3>
    <%= line_chart charts_bitcoin_avg_btc_close_yearly_path, refresh: 60 %>
</div>