config/routes.rb
Rails.application.routes.draw do
  root "home#index"

  get '/login', :to => 'sessions#new', :as => 'login'
  post '/login', :to => 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/password-reset', to: 'passwords#new', as: 'new_password_reset'
  post '/password-reset', to: 'passwords#create', as: 'password_reset'

  get '/password-confirmation', to: 'confirmations#new', as: 'new_password'
  post '/password-confirmation', to: 'passwords#update', as: 'edit_password'

  post 'tokens' => 'tokens#create'

  resources :users, only: [:new, :create, :edit, :update]

  resources :currencies, only: [:show], id: "bitcoin"
  resources :bitcoin, only: [:index]
  resources :ethereum, only: [:index]

  namespace :charts do
    namespace :bitcoin do
      get "avg_btc_open_monthly"
      get "avg_btc_open_yearly"
      get "avg_btc_high_monthly"
      get "avg_btc_high_yearly"
      get "avg_btc_low_monthly"
      get "avg_btc_low_yearly"
      get "avg_btc_close_monthly"
      get "avg_btc_close_yearly"
    end
    namespace :ethereum do
      get "avg_eth_open_monthly"
      get "avg_eth_open_yearly"
      get "avg_eth_high_monthly"
      get "avg_eth_high_yearly"
      get "avg_eth_low_monthly"
      get "avg_eth_low_yearly"
      get "avg_eth_close_monthly"
      get "avg_eth_close_yearly"
    end
  end
end

app/views/layouts/_navbar.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>BEN ticker Dashboard</title>
  <!-- Bootstrap core CSS-->
  <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
  <!-- Custom fonts for this template-->
  <link href="vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
  <!-- Custom styles for this template-->
  <link href="css/sb-admin.css" rel="stylesheet">
</head>

<body class="fixed-nav sticky-footer bg-dark" id="page-top">
  <!-- Navigation-->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" id="mainNav">
    <a class="navbar-brand" href="/currencies/Bitcoin">My Dashboard</a>
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav navbar-sidenav" id="exampleAccordion">
        <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Bitcoin">
          <%= link_to 'Bitcoin', bitcoin_index_path, class: "nav-link" %>
            <i class="fa fa-fw fa-dashboard"></i>
          </a>
        </li>
        <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Ethereum">
          <%= link_to 'Ethereum', ethereum_index_path, class: "nav-link" %>
            <i class="fa fa-fw fa-area-chart"></i>
          </a>
        </li>
        <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Nasdaq">
          <%= link_to 'Nasdaq', currency_path('Nasdaq'), class: "nav-link" %>
            <i class="fa fa-fw fa-table"></i>
          </a>
        </li>
      </ul>
    </div>
  </nav>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BEN ticker</title>
    <%= csrf_meta_tags %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag "https://www.gstatic.com/charts/loader.js" %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans+Condensed:300" rel="stylesheet">
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand mb-0" href="/">BEN ticker</a>
      <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
           <ul class="nav navbar-nav navbar-right bg-dark">
            <% if current_user %>
            <%= link_to "Welcome, #{current_user.first_name}", root_path, class: "nav-link" %>
            <%= link_to 'Logout', logout_path, method: :delete, class: "nav-link" %>
            <% end %>
           </ul>
         </div>

    </nav>
    <div class="container-fluid">
      <%if @error then %>
        <div class="alert alert-error"><%=@error%></div>
       <% end %>
    <%= yield %>
    </div>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>  </body>
  <footer id="fh5co-footer ">
    <div class= "container">
      <div class="col-md-12">
        <p>&copy; BEN ticker - 2017 Sammy Stylez All Rights Reserved. </p>
      </div>
    </div>
  </footer>
</html>